### ISSUE TITLE
Expose triggers for playback stop

### ISSUE THREAD

**Issue by vvv-ca** [RoonLabs/node-roon-api-source-control#1]
I would like to be able to mute/unmute my amp on play/stop events. 
So far the source control allows me to use the convenience_switch to unmute the amp on playback start but there doesn't seem to be any event flowing back on playback stop. 
I would really like to avoid polling the state of a zone via the transport API every second to get this done.
Thanks!

**Comment by dannyfiresnake** [comment]
When you subscribe to the st

**Comment by dannyfiresnake** [comment]
Oops sorry, when you subscribe to the state, it'll respond back multiple times on state changes.

**Comment by vvv-ca** [comment]
Ah, missed that, thanks!
What are the valid zone states? I see playing and paused, is there a case where the state is stopped or something else?

**Comment by dannyfiresnake** [comment]
"playing", "paused", "loading", or "stopped"

**Comment by dannyfiresnake** [comment]
hit cmd/control-t to stop, or longpress the pause icon

loading is common for slow NAS/network or for TIDAL

**Comment by vvv-ca** [comment]
Thanks!
