### ISSUE TITLE
SourceControl not deleted correctly

### ISSUE THREAD

**Issue by bsc101** [RoonLabs/node-roon-api-source-control#2]
Hi there,
found a little bug: in function destroy():
`this._svc.send_continue_all('subscribe_controls', "Changed", { controls_removed: [ o.control_key ] });`
should be:
`this._svc.send_continue_all('subscribe_controls', "Changed", { controls_removed: [ o.state.control_key ] });`
Thanks for fixing!

**Comment by bsc101** [comment]
Any chance to get this fixed?

**Comment by blucz** [comment]
Sorry for the delay. Just pushed the change. Thanks!
