### ISSUE TITLE
Roon v1.8 external source_controls no longer visible

### ISSUE THREAD

**Issue by LINVALE** [RoonLabs/node-roon-api-source-control#4]
![image](https://user-images.githubusercontent.com/1067655/107526556-f4fd5e80-6b85-11eb-8142-1cee8c0b02d9.png)
Since v1.8 was released external source controls added to an output are no longer visible when supports_standby property is true on the source_control device object.

**Comment by dannyfiresnake** [comment]
I personally use the Meridian extension, and it implements standby -- it works perfectly with 1.8.

This is an issue with your extension or setup, not with Roon 1.8.

**Comment by LINVALE** [comment]
I think this is seen when more than one source control is added to an output. An artefact of the changes made a couple of years ago I think which make this possible  and it seems accepted  by you.  It's very  helpful if you want to control more than a single device when switching and not apparent if used as in your Meridian scripts which I have looked at carefully. This has been replicated by others so it would be helpful to either specify that this wasn't the intent or perhaps work with us to clarify how to implement the API as you designed   - which I greatly  appreciate.   Thanks for looking at this - the back and forth in the support  forum may help or I am happy to provide my very imperfect code!

**Comment by LINVALE** [comment]
I put together a small script that illustrates this. It adds three source controls - these do nothing other than switch between selected and standby status. Each on their own works. If you add any one to the zone the space where you would previously see all the buttons appears but none are shown. Remove and again it functions as expected.

Here's the code (vanilla JS) :

[Demo.zip](https://github.com/RoonLabs/node-roon-api-source-control/files/5976194/Demo.zip)

If I am misunderstanding how this should be used I'd be very keen  to know the thinking - it was very useful in previous versions.

Thanks for your response.

**Comment by blucz** [comment]
Thanks @LINVALE . This looks like an unintended consequence of the UI changes. I believe that the controls are still there, just you can't see the buttons.

**Comment by LINVALE** [comment]
Thank you for your response. It is much appreciated and I would be very happy to support any beta testing in the future.

**Comment by LINVALE** [comment]
Thanks Brian.
Appreciate the response and hopefully the team will be able to correct this. I use this in an extension that I'm hoping to release for testing in the community shortly - I held back in anticipation that 1.8 might have some bugs that would be better sorted before asking for my own product to be tested. I'm please i did but anxious to be able to move forwards. In the meanwhile it's made me look more carefully at how source controls work in various extensions that are published and how they relate to 3rd party devoice controls. I'm sure you are aware the documentation is far from clear on this in the API. "Convenience-switch" and "standby" being very specific terms that I must be familiar to the team in Roonlabs , but not to someone like me who is trying to understand the use of the API. I want to  provide an experience for users that doesn't detract from the amazing overall experience I and others have had with Roon over the past couple of years.
Please do let me know if I can test or help with this as you move forwards.
Best
Peter
    On Saturday, February 13, 2021, 04:35:36 PM EST, Brian Luczkiewicz <notifications@github.com> wrote:  
 
 


Thanks @LINVALE . This looks like an unintended consequence of the UI changes. I believe that the controls are still there, just you can't see the buttons.

**Comment by LINVALE** [comment]
Thanks.
I can confirm this is now fixed with todays release of build 763.
Peter
    On Monday, February 15, 2021, 10:02:27 AM EST, Peter Richardson <petercrichardson@yahoo.com> wrote:  
 
  Thanks Brian.
Appreciate the response and hopefully the team will be able to correct this. I use this in an extension that I'm hoping to release for testing in the community shortly - I held back in anticipation that 1.8 might have some bugs that would be better sorted before asking for my own product to be tested. I'm please i did but anxious to be able to move forwards. In the meanwhile it's made me look more carefully at how source controls work in various extensions that are published and how they relate to 3rd party devoice controls. I'm sure you are aware the documentation is far from clear on this in the API. "Convenience-switch" and "standby" being very specific terms that I must be familiar to the team in Roonlabs , but not to someone like me who is trying to understand the use of the API. I want to  provide an experience for users that doesn't detract from the amazing overall experience I and others have had with Roon over the past couple of years.
Please do let me know if I can test or help with this as you move forwards.
Best
Peter
    On Saturday, February 13, 2021, 04:35:36 PM EST, Brian Luczkiewicz <notifications@github.com> wrote:  
 
 


Thanks @LINVALE . This looks like an unintended consequence of the UI changes. I believe that the controls are still there, just you can't see the buttons.

**Comment by LINVALE** [comment]
This has been resolved with the release of build 763.

Thank you!
